import './globals.scss'
import 'bootstrap/dist/css/bootstrap.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div className='main-wrapper'>
          {children}
        </div>
      </body>
    </html>
  )
}
